version: "3.9"

services:

  db:
    image: postgres:16
    container_name: digital-fd-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - fd-network

  backend:
    image: digital-fd-backend:1.0
    container_name: digital-fd-backend
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

      # Google OAuth
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}

    ports:
      - "8080:8080"
    networks:
      - fd-network

  frontend:
    image: digital-fd-frontend:1.0
    container_name: digital-fd-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - fd-network

volumes:
  db_data:

networks:
  fd-network:
    driver: bridge
